### ISSUE TITLE
Nuxt 3.8.1

### ISSUE THREAD

**Issue by bayramorhan** [johannschopplich/nuxt-gtag#32]
### Environment

Nuxt 3.8.1

### Reproduction

Local Dev

### Describe the bug

Im getting this error as soon as activate the plugin. Everyting works perfect when I remove this plugin from the nuxt.config.js

```
nuxt.js:97 [nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'id')
    at plugin.client.mjs:5:13
    at nuxt.js:110:60
    at fn (nuxt.js:153:44)
    at Object.runWithContext (runtime-core.esm-bundler.js:3873:18)
    at callWithNuxt (nuxt.js:158:24)
    at nuxt.js:31:54
    at EffectScope.run (reactivity.esm-bundler.js:38:16)
    at Object.runWithContext (nuxt.js:31:44)
    at applyPlugin (nuxt.js:110:39)
    at applyPlugins (nuxt.js:125:21)
```

**Comment by thelfensdrfer** [comment]
It would have been really helpful to provide a solution before closing the issue :/
