### ISSUE TITLE
Cannot run the Nuxt app after installing this package

### ISSUE THREAD

**Issue by XenBG** [johannschopplich/nuxt-gtag#6]
### Environment

- Operating System: `Linux`
- Node Version:     `v19.8.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `ssr`, `experimental`, `postcss`, `modules`, `gtag`, `i18n`
- Runtime Modules:  `@vueuse/nuxt@9.13.0`, `@nuxtjs/i18n@8.0.0-beta.7-27867903.cc6cc78`, `nuxt-gtag@0.3.0`, `nuxt-schema-org@2.1.2`, `@funken-studio/sitemap-nuxt-3@4.0.4`, `@pinia/nuxt@0.4.7`
- Build Modules:    `-`

### Reproduction

I can't provide a link because my Node version is v19.8.1, but in StackBlitz is v16.14.2 and there it is working, so maybe the problem comes from the Node version.

### Describe the bug

```
Nuxt 3.3.1 with Nitro 2.3.2
  > Local:    http://localhost:3000/ 
  > Network:  http://172.18.0.1:3000/
  > Network:  http://192.168.10.110:3000/

 ERROR  Cannot start nuxt:  The "name" argument must be specified

  at new NodeError (node:internal/errors:399:5)
  at Performance.mark (node:internal/perf/performance:125:13)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:168:30)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:451:15)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2469:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6843:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6873:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
```

**Comment by johannschopplich** [comment]
Thanks for reporting! This is actually a bug in Nuxt itself: https://github.com/nuxt/nuxt/pull/19687

Nuxt v3.3.2 is around the corner with the fix above provided: https://github.com/nuxt/nuxt/pull/19875
